version: '3.3'
services:
  backend:
    image: "dto80/234-lab11:latest"
    ports:
      - "8084:8080"
  frontend:
    image: "592115514/lab234-lab11-frontend:latest"
    ports:
      - "8087:80"
  

