version: '3.3'
services:
  backend:
    image: dto80/234-lab11:latest
    ports:
      - "8085:8080"
    volumes:
      - type: bind
        source: ./data
        target: /data
  frontend:
    image: 592115514/lab234-lab11-frontend
    ports:
      - "8087:80"

